### ISSUE TITLE
Memberof not populating

### ISSUE THREAD

**Issue by nikirago** [rroemhild/docker-test-openldap#18] opened 2020-09-23 20:30 UTC
Hello, looks like memberof configuration is not populating under user records. Is that expected or is there anything needed to be done to get that to work?

**Comment by satterly** [comment] 2020-11-03 19:43
It works for this LDAP search...
```
$ ldapsearch -H ldap://localhost:389 \
  -D cn=admin,dc=planetexpress,dc=com \
  -w GoodNewsEveryone \
  -b "ou=people,dc=planetexpress,dc=com" \
  -s sub \
  "(&(uid=professor)(objectClass=inetOrgPerson))" \
  "memberOf"
ldap_initialize( ldap://localhost:389/??base )
filter: (&(uid=professor)(objectClass=inetOrgPerson))
requesting: memberOf
# extended LDIF
#
# LDAPv3
# base <ou=people,dc=planetexpress,dc=com> with scope subtree
# filter: (&(uid=professor)(objectClass=inetOrgPerson))
# requesting: memberOf
#

# Hubert J. Farnsworth, people, planetexpress.com
dn: cn=Hubert J. Farnsworth,ou=people,dc=planetexpress,dc=com
memberOf: cn=admin_staff,ou=people,dc=planetexpress,dc=com

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

What search filter are you using?

**Comment by stiller-leser** [comment] 2020-11-27 14:37
I suppose the issue is a little different. While you can request the attribute with @satterly's `ldapsearch` the `memberOf` attribute is never returned for `inetOrgPerson` for a `ldapsearch` that is not requesting it. All other fields are.
 
Trying to add it into https://github.com/rroemhild/docker-test-openldap/blob/master/bootstrap/config/msad.ldif#L19 results in 
```
ldap_modify: Other (e.g., implementation specific) error (80)
        additional info: olcObjectClasses: AttributeType not found: "memberOf"
```

**Comment by rroemhild** [comment] 2021-01-03 16:57
Hi @nikirago, `memberof` is an operation attribute and not returned by the server per default. You can return it explicit as in the example from @satterly or add the `+` sign at the end of your ldapsearch command:

```sh
ldapsearch -H ldap://localhost:10389 \
    -D cn=admin,dc=planetexpress,dc=com \
    -w GoodNewsEveryone \
    -b "ou=people,dc=planetexpress,dc=com" \
    -s sub "(&(uid=professor)(objectClass=inetOrgPerson))" +
```

I'll close this issue. Feel free to re-open it if you still can't get the `memberOf` attribute.

**Closed by rroemhild** 2021-01-03 16:57 UTC
